import { Routes, Route, Navigate } from 'react-router-dom';
import { useState, useEffect, createContext, useContext, Component, type ReactNode, type ErrorInfo } from 'react';
import { ThemeProvider } from './contexts/ThemeContext';
import { TenantProvider } from './contexts/TenantContext';
import Layout from './components/layout/Layout';
import Dashboard from './pages/Dashboard';
import AgentChat from './pages/AgentChat';
import Agents from './pages/Agents';
import Orchestrator from './pages/Orchestrator';
import Tools from './pages/Tools';
import Cron from './pages/Cron';
import Integrations from './pages/Integrations';
import Memory from './pages/Memory';
import Knowledge from './pages/Knowledge';
import Config from './pages/Config';
import Cost from './pages/Cost';
import Logs from './pages/Logs';
import Doctor from './pages/Doctor';
import Pairing from './pages/Pairing';
import Canvas from './pages/Canvas';
import Jarvis from './pages/Jarvis';
import { AuthProvider, useAuth } from './hooks/useAuth';
import { DraftContext, useDraftStore } from './hooks/useDraft';
import { setLocale, type Locale } from './lib/i18n';
import { loadLocale, saveLocale } from './contexts/ThemeContext';
import { basePath } from './lib/basePath';
import { getAdminPairCode, requestAccess } from './lib/api';

// Locale context
interface LocaleContextType {
  locale: string;
  setAppLocale: (locale: string) => void;
}

export const LocaleContext = createContext<LocaleContextType>({
  locale: 'en',
  setAppLocale: () => {},
});

export const useLocaleContext = () => useContext(LocaleContext);

// ---------------------------------------------------------------------------
// Error boundary — catches render crashes and shows a recoverable message
// instead of a black screen
// ---------------------------------------------------------------------------

interface ErrorBoundaryState {
  error: Error | null;
}

export class ErrorBoundary extends Component<
  { children: ReactNode },
  ErrorBoundaryState
> {
  constructor(props: { children: ReactNode }) {
    super(props);
    this.state = { error: null };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { error };
  }

  componentDidCatch(error: Error, info: ErrorInfo) {
    console.error('[ZeroClaw] Render error:', error, info.componentStack);
  }

  render() {
    if (this.state.error) {
      return (
        <div className="p-6">
          <div className="card p-6 w-full max-w-lg" style={{ borderColor: 'rgba(239, 68, 68, 0.3)' }}>
            <h2 className="text-lg font-semibold mb-2" style={{ color: 'var(--color-status-error)' }}>
              Something went wrong
            </h2>
            <p className="text-sm mb-4" style={{ color: 'var(--pc-text-muted)' }}>
              A render error occurred. Check the browser console for details.
            </p>
            <pre className="text-xs rounded-lg p-3 overflow-x-auto whitespace-pre-wrap break-all font-mono" style={{ background: 'var(--pc-bg-base)', color: 'var(--color-status-error)' }}>
              {this.state.error.message}
            </pre>
            <button
              onClick={() => this.setState({ error: null })}
              className="btn-electric mt-6 px-4 py-2 text-sm font-medium"
            >
              Try again
            </button>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}

// Pairing dialog component — entry surface for unauthenticated visitors.
// Two tabs:
//   • "Pair" (operator path): paste a 6-digit code generated by the daemon
//   • "Request access" (public path): submit name/email/use-case for the
//     operator to approve from the /pairing admin console
// Default tab is auto-selected from context: if a code is in the URL or
// returned by /admin/paircode (i.e. an operator just clicked the QR deep
// link or is on localhost), open the Pair tab pre-filled. Otherwise open
// the Request tab — the visitor likely has no code.
type LoginTab = 'pair' | 'request';

function PairingDialog({ onPair }: { onPair: (code: string) => Promise<void> }) {
  const [tab, setTab] = useState<LoginTab>('request');
  const [tabExplicit, setTabExplicit] = useState(false); // user clicked tab → don't auto-flip
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [displayCode, setDisplayCode] = useState<string | null>(null);
  const [codeLoading, setCodeLoading] = useState(true);

  // Request-access form state
  const [reqName, setReqName] = useState('');
  const [reqEmail, setReqEmail] = useState('');
  const [reqUseCase, setReqUseCase] = useState('');
  const [reqSubmitting, setReqSubmitting] = useState(false);
  const [reqSubmitted, setReqSubmitted] = useState(false);
  const [reqError, setReqError] = useState('');

  // Source priority for the pairing code, in order:
  // 1. `?pair=NNNNNN` URL query — set by the QR-scan deep link from
  //    the admin panel. This is how a brand-new remote device gets
  //    the code without typing it.
  // 2. `/admin/paircode` — works on localhost (no auth) so the
  //    operator who just ran the daemon doesn't have to grep logs.
  // 3. Manual entry — the field stays empty, the user types.
  useEffect(() => {
    // 1) URL param wins
    try {
      const params = new URLSearchParams(window.location.search);
      const fromUrl = params.get('pair');
      if (fromUrl && /^\d{6}$/.test(fromUrl)) {
        setDisplayCode(fromUrl);
        setCode(fromUrl);
        setCodeLoading(false);
        if (!tabExplicit) setTab('pair');
        // Strip the query so a refresh doesn't keep showing it after pair
        window.history.replaceState({}, '', window.location.pathname);
        return;
      }
    } catch {
      // ignore
    }

    // 2) Admin endpoint (localhost-only in production; useful for dev)
    let cancelled = false;
    getAdminPairCode()
      .then((data) => {
        if (!cancelled && data.pairing_code) {
          setDisplayCode(data.pairing_code);
          setCode(data.pairing_code); // auto-fill so user just clicks "Pair"
          if (!tabExplicit) setTab('pair');
        }
      })
      .catch(() => {
        // Endpoint not reachable from a remote browser — that's fine,
        // the code is shown on the admin panel of an already-paired
        // device (or the operator's terminal). Public visitors stay on
        // the "Request access" tab (the default).
      })
      .finally(() => {
        if (!cancelled) setCodeLoading(false);
      });
    return () => { cancelled = true; };
    // tabExplicit guards against auto-flipping after the user picks a tab.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      await onPair(code);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Pairing failed');
    } finally {
      setLoading(false);
    }
  };

  const handleRequest = async (e: React.FormEvent) => {
    e.preventDefault();
    setReqSubmitting(true);
    setReqError('');
    try {
      await requestAccess(reqName.trim(), reqEmail.trim(), reqUseCase.trim());
      setReqSubmitted(true);
    } catch (err: unknown) {
      setReqError(err instanceof Error ? err.message : 'Request failed');
    } finally {
      setReqSubmitting(false);
    }
  };

  const pickTab = (next: LoginTab) => {
    setTabExplicit(true);
    setTab(next);
    setError('');
    setReqError('');
  };

  const tabBtnStyle = (active: boolean) => ({
    background: active ? 'var(--pc-accent-glow)' : 'transparent',
    borderColor: active ? 'var(--pc-accent)' : 'var(--pc-border)',
    color: active ? 'var(--pc-text-primary)' : 'var(--pc-text-muted)',
    fontWeight: active ? 600 : 400,
  });

  return (
    <div className="min-h-screen flex items-center justify-center" style={{ background: 'var(--pc-bg-base)' }}>
      <div className="relative surface-panel p-8 w-full max-w-md animate-fade-in-scale">

        <div className="text-center mb-6">
          <img
            src={`${basePath}/_app/zeroclaw-trans.png`}
            alt="Octopus Labs"
            className="h-20 w-20 rounded-2xl object-cover mx-auto mb-4 animate-float"
            onError={(e) => { e.currentTarget.style.display = 'none'; }}
          />
          <h1 className="text-2xl font-bold mb-2 text-gradient-blue">Octopus Labs</h1>
          <p className="text-sm" style={{ color: 'var(--pc-text-muted)' }}>
            {tab === 'pair'
              ? (displayCode ? 'Your pairing code — click Pair to connect' : 'Enter the pairing code from your terminal')
              : 'Request access — the operator will issue a code when approved'}
          </p>
        </div>

        {/* Tab toggle */}
        <div className="flex gap-2 mb-6">
          <button
            type="button"
            onClick={() => pickTab('request')}
            className="flex-1 px-3 py-2 text-xs rounded-lg border transition-all"
            style={tabBtnStyle(tab === 'request')}
          >
            Request access
          </button>
          <button
            type="button"
            onClick={() => pickTab('pair')}
            className="flex-1 px-3 py-2 text-xs rounded-lg border transition-all"
            style={tabBtnStyle(tab === 'pair')}
          >
            I have a code
          </button>
        </div>

        {tab === 'pair' ? (
          <>
            {/* Show the pairing code if available (localhost) */}
            {!codeLoading && displayCode && (
              <div className="mb-6 p-4 rounded-2xl text-center border" style={{ background: 'var(--pc-accent-glow)', borderColor: 'var(--pc-accent-dim)' }}>
                <div className="text-4xl font-mono font-bold tracking-[0.4em] py-2" style={{ color: 'var(--pc-text-primary)' }}>
                  {displayCode}
                </div>
                <p className="text-xs mt-2" style={{ color: 'var(--pc-text-muted)' }}>Enter this code below or on another device</p>
              </div>
            )}

            <form onSubmit={handleSubmit}>
              <input
                type="text"
                value={code}
                onChange={(e) => setCode(e.target.value)}
                placeholder="6-digit code"
                className="input-electric w-full px-4 py-4 text-center text-2xl tracking-[0.3em] font-medium mb-4"
                maxLength={6}
                autoFocus
              />
              {error && (
                <p aria-live="polite" className="text-sm mb-4 text-center animate-fade-in" style={{ color: 'var(--color-status-error)' }}>{error}</p>
              )}
              <button
                type="submit"
                disabled={loading || code.length < 6}
                className="btn-electric w-full py-3.5 text-sm font-semibold tracking-wide"
              >
                {loading ? (
                  <span className="flex items-center justify-center gap-2">
                    <span className="h-4 w-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Pairing...
                  </span>
                ) : 'Pair'}
              </button>
            </form>
          </>
        ) : reqSubmitted ? (
          <div className="text-center py-6 animate-fade-in">
            <div
              className="mx-auto mb-4 h-12 w-12 rounded-full flex items-center justify-center text-xl"
              style={{ background: 'var(--pc-accent-glow)', color: 'var(--pc-accent)' }}
            >
              ✓
            </div>
            <p className="text-sm mb-2" style={{ color: 'var(--pc-text-primary)' }}>
              Request submitted
            </p>
            <p className="text-xs mb-6" style={{ color: 'var(--pc-text-muted)' }}>
              The operator will issue a pairing code and contact you at <strong>{reqEmail}</strong>.
              Keep this tab open or come back and enter the code in <em>I have a code</em>.
            </p>
            <button
              type="button"
              onClick={() => {
                setReqSubmitted(false);
                setReqName('');
                setReqEmail('');
                setReqUseCase('');
              }}
              className="text-xs underline"
              style={{ color: 'var(--pc-text-muted)' }}
            >
              Submit another request
            </button>
          </div>
        ) : (
          <form onSubmit={handleRequest} className="space-y-3">
            <div>
              <label className="block text-xs mb-1" style={{ color: 'var(--pc-text-muted)' }}>Name</label>
              <input
                type="text"
                value={reqName}
                onChange={(e) => setReqName(e.target.value)}
                placeholder="Your name"
                className="input-electric w-full px-3 py-2.5 text-sm"
                maxLength={500}
                required
                autoFocus
              />
            </div>
            <div>
              <label className="block text-xs mb-1" style={{ color: 'var(--pc-text-muted)' }}>Email</label>
              <input
                type="email"
                value={reqEmail}
                onChange={(e) => setReqEmail(e.target.value)}
                placeholder="you@example.com"
                className="input-electric w-full px-3 py-2.5 text-sm"
                maxLength={500}
                required
              />
            </div>
            <div>
              <label className="block text-xs mb-1" style={{ color: 'var(--pc-text-muted)' }}>How will you use this?</label>
              <textarea
                value={reqUseCase}
                onChange={(e) => setReqUseCase(e.target.value)}
                placeholder="A short note for the operator (one or two sentences)."
                className="input-electric w-full px-3 py-2.5 text-sm"
                maxLength={500}
                rows={3}
                required
              />
            </div>
            {reqError && (
              <p aria-live="polite" className="text-sm text-center animate-fade-in" style={{ color: 'var(--color-status-error)' }}>{reqError}</p>
            )}
            <button
              type="submit"
              disabled={reqSubmitting || !reqName.trim() || !reqEmail.trim() || !reqUseCase.trim()}
              className="btn-electric w-full py-3 text-sm font-semibold tracking-wide"
            >
              {reqSubmitting ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="h-4 w-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  Sending...
                </span>
              ) : 'Request access'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}

function AppContent() {
  const { isAuthenticated, requiresPairing, loading, pair, logout } = useAuth();
  const [locale, setLocaleState] = useState(loadLocale());
  const draftStore = useDraftStore();
  setLocale(locale as Locale);

  const setAppLocale = (newLocale: string) => {
    setLocaleState(newLocale);
    setLocale(newLocale as Locale);
    saveLocale(newLocale);
  };

  // Listen for 401 events to force logout
  useEffect(() => {
    const handler = () => {
      logout();
    };
    window.addEventListener('zeroclaw-unauthorized', handler);
    return () => window.removeEventListener('zeroclaw-unauthorized', handler);
  }, [logout]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ background: 'var(--pc-bg-base)' }}>
        <div className="flex flex-col items-center gap-4 animate-fade-in">
          <div className="h-10 w-10 border-2 rounded-full animate-spin" style={{ borderColor: 'var(--pc-border)', borderTopColor: 'var(--pc-accent)' }} />
          <p className="text-sm" style={{ color: 'var(--pc-text-muted)' }}>Connecting...</p>
        </div>
      </div>
    );
  }

  if (!isAuthenticated && requiresPairing) {
    return <PairingDialog onPair={pair} />;
  }

  return (
    <DraftContext.Provider value={draftStore}>
      <LocaleContext.Provider value={{ locale, setAppLocale }}>
        <Routes>
          {/* Jarvis is rendered outside the Layout chrome so the orb
              can occupy the full viewport. */}
          <Route path="/jarvis" element={<Jarvis />} />
          <Route element={<Layout />}>
            <Route path="/" element={<Dashboard />} />
            <Route path="/agent" element={<AgentChat />} />
            <Route path="/agents" element={<Agents />} />
            <Route path="/orchestrator" element={<Orchestrator />} />
            <Route path="/tools" element={<Tools />} />
            <Route path="/cron" element={<Cron />} />
            <Route path="/integrations" element={<Integrations />} />
            <Route path="/memory" element={<Memory />} />
            <Route path="/knowledge" element={<Knowledge />} />
            <Route path="/config" element={<Config />} />
            <Route path="/cost" element={<Cost />} />
            <Route path="/logs" element={<Logs />} />
            <Route path="/doctor" element={<Doctor />} />
            <Route path="/pairing" element={<Pairing />} />
            <Route path="/canvas" element={<Canvas />} />
            <Route path="*" element={<Navigate to="/" replace />} />
          </Route>
        </Routes>
      </LocaleContext.Provider>
    </DraftContext.Provider>
  );
}

export default function App() {
  return (
    <AuthProvider>
      <ThemeProvider>
        <TenantProvider>
          <AppContent />
        </TenantProvider>
      </ThemeProvider>
    </AuthProvider>
  );
}
